### ISSUE TITLE
strange BBOX format in relationship annotation

### ISSUE THREAD

**Issue by czqInNanjing** [jz462/Large-Scale-VRD.pytorch#13]
Hello, thank you for your great job! It is very helpful.

I just wonder why the bbox format of the subject and object in relationship annotation is y1y2x1x2 rather than xywh or x1y1x2y2, which makes me very confuse.

I spend sometime fixing this bug since it is sometimes very difficult to notice small errors that seems to be right.

I think it would be better to highlight this special thing in the readme.

**Comment by jz462** [comment]
Hi @czqInNanjing,

The y1y2x1x2 format is kept merely for the reason that when I was doing the project I needed to take care of OpenImages, Visual Genome and VRD datasets at the same time, and I chose this one to be consistent across the three datasets. I strongly suggest not to change the default format in the code but instead modify your dataset to fit in this format, which is definitely less risky.

Ji
