### ISSUE TITLE
Error occurs when training detection model

### ISSUE THREAD

**Issue by inrainbws** [jz462/Large-Scale-VRD.pytorch#3]
Hi, thanks for this wonderful work!
I am trying to train the object detector on GQA and prepared the dataset in COCO format. When I run `python ./tools/train_net_step.py --dataset gqa_150_50 --cfg configs/e2e_faster_rcnn_X-101-64x4d-FPN_1x_vg.yaml --nw 8 --use_tfboard`, this error occurred:

```
INFO model_builder.py: 129: loading detectron pretrained weights from data/detectron_model/X-101-64x4d.pkl
Traceback (most recent call last):
  File "./tools/train_net_step.py", line 457, in <module>
    main()
  File "./tools/train_net_step.py", line 268, in main
    maskRCNN = Generalized_RCNN()
  File "/home/yzhq/codespace/lsvrd-origin/lib/modeling/model_builder.py", line 115, in __init__
    self._init_modules()
  File "/home/yzhq/codespace/lsvrd-origin/lib/modeling/model_builder.py", line 143, in _init_modules
    if cfg.RESNETS.OI_PRETRAINED_WEIGHTS != '':
  File "/home/yzhq/codespace/lsvrd-origin/lib/utils/collections.py", line 38, in __getattr__
    raise AttributeError(name)
AttributeError: OI_PRETRAINED_WEIGHTS
```

Could you please provide info about how this can be fixed?

**Comment by inrainbws** [comment]
update: simply commenting out related lines in `lib/modeling/model_builder.py` solves the problem

**Comment by jz462** [comment]
Hi @yzhq97,

Glad you solved it! I think you are probably using an old version of this repo which has this redundant line of code. I have updated the code and now it should be good to go.

**Comment by norajoby** [comment]
I also had to comment this part to run training of object detector for VG dataset:
```
        if cfg.RESNETS.TO_BE_FINETUNED_WEIGHTS != '':
            logger.info("loading trained and to be finetuned weights from %s", cfg.RESNETS.TO_BE_FINETUNED_WEIGHTS)
            checkpoint = torch.load(cfg.RESNETS.TO_BE_FINETUNED_WEIGHTS, map_location=lambda storage, loc: storage)
            net_utils.load_ckpt(self, checkpoint['model'])

```
